### ISSUE TITLE
The code is actually unmaintainable

### ISSUE THREAD

**Issue by mohebifar** [miladdavoodi/vidmotionjs#1]
Having a short glance at your code, I have to admit that it is terrible.

No proper code styling, variable names sound gibberish, poor API,etc. are some cases in point.

**Comment by sallar** [comment]
I agree. The code needs to be re-written from scratch. And please, use a linter like ESLint or XO. Some notes about the code:

- Your variables are vague and unreadable. Use proper variable naming schemes. 
- Indentation, spacing and number of empty lines are off. 
- Using a global jQuery dependency is a bad idea: `$('#click')` <- This is bad-practice

The code looks like a minified version of some code that has been prettified and changed. Your code needs to be genuine and trustworthy.

Good luck!

**Comment by mamal72** [comment]
> The code looks like a minified version of some code that has been prettified and changed. Your code needs to be genuine and trustworthy.

Agree, same feeling here. asked for some explanation but got nothing.

**Comment by bluetec** [comment]
Currently the code is nonsense. All opinions of these cool guys are right and should be applied.

**Comment by mamal72** [comment]
The main repo's [here](https://github.com/m90/seeThru) guys. [More info](https://twitter.com/mamal72/status/756163488171565056).
